### ISSUE TITLE
Praise

### ISSUE THREAD

**Issue by rafi** [wadackel/vim-dogrun#6]
Well-done, I find this colorscheme very pleasing to the eye. And I do love purple. I suggest changing the GitHub repository tagline from _"dark neo/vim colorschemes for the GUI / .."_ to something less general and more personal.. like _"fantastic dark vim colorscheme for the intergalactic space programmer"_  😉

Just out of curiosity, why did you write the rust generator for the code in the `colors/dogrun.vim` file?  why create another abstraction?

**Comment by wadackel** [comment]
Hi @rafi, Thanks for your interest in this colorscheme!

> something less general and more personal.. like

Wow, I'm feeling a little embarrassed, so let's just tagline this as it is... :)

---

> why did you write the rust generator for the code in the colors/dogrun.vim file? why create another abstraction?

Good question.

`dogrun` automatically generates a cterm color. This is to maintain excellent maintenance.

Doing this calculation dynamically in Vimscript will increase the time it takes to load the color scheme. In order to optimize performance, we created a generator :+1:

Inspired by the [rhysd/vim-color-spring-night](https://github.com/rhysd/vim-color-spring-night).
